import { TRIGGER_HINT } from '@agent-spawner/compiler';
import { agentSpecSchema } from '@agent-spawner/spec';
import type {
  AgentSpec,
  EnvVar,
  KnowledgeItem,
  McpServer,
  Skill,
  SubAgent,
  Trigger,
  Workflow,
} from '@agent-spawner/spec';
import { parseBool, parseFrontmatter, parseList, parseNumber } from './frontmatter.ts';

export type SourceFile = { path: string; content: string; sizeBytes?: number };

export type DecompileResult = {
  spec: AgentSpec;
  /** Anything the importer could not place. Surfaced in the UI so nothing is lost silently. */
  unhandled: Array<{ path: string; reason: string }>;
};

/**
 * files → spec. The inverse of the compiler, used to import an existing plugin into the editor.
 *
 * For a bundle this tool produced, `compile(decompile(files))` reproduces `files` byte for byte —
 * that fixed point is what the round-trip test asserts. Spec-level equality is *not* claimed:
 * ids, storage keys and deployment settings are editor state that never reaches the bundle, so
 * they cannot be recovered from it.
 *
 * Everything read here is untrusted content. It is parsed as data and never executed.
 */
export function decompile(files: SourceFile[]): DecompileResult {
  const byPath = new Map(files.map((f) => [normalize(f.path), f]));
  const unhandled: Array<{ path: string; reason: string }> = [];
  const read = (path: string) => byPath.get(path)?.content;

  const manifest = readJson(read('.claude-plugin/plugin.json')) ?? {};
  const slug = str(manifest.name) || 'imported-plugin';

  // ── meta ────────────────────────────────────────────────────────────────────
  const author = obj(manifest.author);
  const readme = read('README.md') ?? '';
  const isGeneratedReadme =
    readme.includes('generated by [Agent Spawner]') || readme.includes('Tracks every commit');

  const meta = {
    name: str(manifest.displayName) || str(manifest.name) || 'Imported plugin',
    slug,
    description: str(manifest.description),
    version: str(manifest.version) || '0.1.0',
    versionMode: manifest.version ? ('pinned' as const) : ('commit-sha' as const),
    author: { name: str(author.name), email: str(author.email), url: str(author.url) },
    license: str(manifest.license) || 'UNLICENSED',
    keywords: arr(manifest.keywords).map(String),
    homepage: str(manifest.homepage),
    repository: str(manifest.repository),
    defaultEnabled: manifest.defaultEnabled !== false,
    readme: {
      mode: isGeneratedReadme ? ('generated' as const) : ('custom' as const),
      body: readme || undefined,
    },
    changelogEntry: parseChangelog(read('CHANGELOG.md')),
    dependencies: arr(manifest.dependencies).map((entry) => {
      const text = String(entry);
      const at = text.lastIndexOf('@');
      // A leading `@` is a scope, not a constraint separator.
      return at > 0
        ? { name: text.slice(0, at), constraint: text.slice(at + 1) }
        : { name: text, constraint: '' };
    }),
  };

  // ── primary agent → goal, workflows, orchestration ──────────────────────────
  const primary = parseFrontmatter(read(`agents/${slug}.md`) ?? '');
  const sections = splitSections(primary.body);

  const goal = {
    statement: stripTone(sections['# Objective'] ?? ''),
    successCriteria: bullets(sections['## Success criteria'] ?? ''),
    outOfScope: bullets(sections['## Out of scope'] ?? ''),
    tone: extractTone(sections['# Objective'] ?? ''),
    primaryModel: primary.fields.model || 'inherit',
    primaryEffort: primary.fields.effort as AgentSpec['goal']['primaryEffort'],
  };

  // ── sub-agents ──────────────────────────────────────────────────────────────
  const agentFiles = [...byPath.keys()]
    .filter((p) => p.startsWith('agents/') && p.endsWith('.md') && p !== `agents/${slug}.md`)
    .sort();

  const subAgents: SubAgent[] = agentFiles.map((path, i) => {
    const { fields, body } = parseFrontmatter(byPath.get(path)!.content);
    const name = fields.name || path.slice('agents/'.length, -3);
    const { description, trigger } = splitTriggerHint(fields.description ?? '');
    const allow = parseList(fields.tools);
    return {
      id: `sa_import_${i}`,
      name,
      description,
      systemPrompt: stripGeneratedAgentSections(body),
      taskIds: [],
      trigger: { kind: trigger },
      tools: {
        mode: allow.length > 0 ? ('allowlist' as const) : ('inherit' as const),
        allow,
        deny: parseList(fields.disallowedTools),
      },
      runtime: {
        model: fields.model || 'inherit',
        effort: fields.effort as SubAgent['runtime']['effort'],
        maxTurns: parseNumber(fields.maxTurns),
        background: parseBool(fields.background) ?? false,
        isolation: fields.isolation === 'worktree' ? ('worktree' as const) : undefined,
        memory: fields.memory as SubAgent['runtime']['memory'],
        contextBudget: 'custom' as const,
      },
      preloadSkillIds: [],
      color: undefined,
    };
  });

  const agentIdByName = new Map(subAgents.map((a) => [a.name, a.id]));

  const workflows = parseWorkflows(sections['# Workflow'] ?? '', agentIdByName);
  for (const workflow of workflows) {
    for (const agentId of workflow.assignedSubAgentIds) {
      subAgents.find((a) => a.id === agentId)?.taskIds.push(workflow.id);
    }
  }

  // A promoted workflow shows as `Run /skill` in the primary agent, so its steps only survive
  // in the assigned-work section of whichever sub-agent owns it.
  const stepsByTitle = new Map<string, string[]>();
  for (const agent of subAgents) {
    const { body } = parseFrontmatter(byPath.get(`agents/${agent.name}.md`)!.content);
    for (const [title, steps] of parseAssignedWork(body)) {
      if (steps.length > 0 && !stepsByTitle.has(title)) stepsByTitle.set(title, steps);
    }
  }
  for (const workflow of workflows) {
    if (workflow.steps.length === 0) workflow.steps = stepsByTitle.get(workflow.title) ?? [];
  }

  const orchestration = parseDelegation(sections['# Delegation'] ?? '', agentIdByName);

  // A directory listing is alphabetical; the delegation stages are the only record of the
  // order the author arranged the agents in, so restore it from there.
  const stageOrder = new Map(orchestration.groups.flatMap((g, gi) => g.subAgentIds.map((id, ai) => [id, gi * 1000 + ai])));
  subAgents.sort(
    (a, b) => (stageOrder.get(a.id) ?? Number.MAX_SAFE_INTEGER) - (stageOrder.get(b.id) ?? Number.MAX_SAFE_INTEGER),
  );

  // ── skills ──────────────────────────────────────────────────────────────────
  const skillPaths = [...byPath.keys()].filter((p) => p.startsWith('skills/') && p.endsWith('/SKILL.md')).sort();
  const skills: Skill[] = [];
  const promotedByName = new Map(
    workflows.filter((w) => w.promoteToSkill).map((w) => [w.skillOverrides?.name ?? '', w]),
  );

  skillPaths.forEach((path, i) => {
    const dir = path.slice('skills/'.length, -'/SKILL.md'.length);
    // The knowledge index skill is regenerated from `knowledge[]`; importing it would duplicate it.
    if (dir === `${slug}-knowledge`) return;

    const { fields, body } = parseFrontmatter(byPath.get(path)!.content);
    const name = fields.name || dir;
    const supporting = [...byPath.keys()]
      .filter((p) => p.startsWith(`skills/${dir}/`) && p !== path)
      .sort()
      .map((p) => ({ path: p.slice(`skills/${dir}/`.length), content: byPath.get(p)!.content }));

    const common = {
      name,
      description: fields.description ?? '',
      whenToUse: fields['when-to-use'] ?? '',
      body: stripSupportingSection(body),
      allowedTools: parseList(fields['allowed-tools']),
      disableModelInvocation: parseBool(fields['disable-model-invocation']) ?? false,
      userInvocable: parseBool(fields['user-invocable']) ?? true,
      model: fields.model,
      effort: fields.effort as Skill['effort'],
      context: fields.context === 'fork' ? ('fork' as const) : undefined,
      agent: fields.agent,
    };

    // A skill whose name matches a promoted workflow belongs to that workflow, not the
    // skills list — otherwise it would be emitted twice on the next compile.
    const workflow = promotedByName.get(name);
    if (workflow) {
      workflow.skillOverrides = { ...workflow.skillOverrides, ...common };
      return;
    }

    skills.push({ id: `sk_import_${i}`, source: 'attached', ...common, files: supporting });
  });

  const skillIdByName = new Map(skills.map((s) => [s.name, s.id]));
  for (const agent of subAgents) {
    const { fields } = parseFrontmatter(byPath.get(`agents/${agent.name}.md`)!.content);
    agent.preloadSkillIds = parseList(fields.skills)
      .map((n) => skillIdByName.get(n))
      .filter((id): id is string => Boolean(id));
  }

  // ── connectors ──────────────────────────────────────────────────────────────
  const mcpServers = parseMcp(read('.mcp.json'), read('.env.example'), primary.fields.tools, readme);
  const primaryTools = parseList(primary.fields.tools).filter(
    (t) => !t.startsWith('mcp__') && t !== 'Agent' && t !== 'Skill',
  );

  const connectors = {
    mcpServers,
    builtinTools: { allow: primaryTools, deny: parseList(primary.fields.disallowedTools) },
    permissionsHint: parsePermissions(readme, mcpServers),
  };

  // ── triggers ────────────────────────────────────────────────────────────────
  const triggers: Trigger[] = [
    ...parseHooks(read('hooks/hooks.json'), byPath),
    ...parseMonitors(read('monitors/monitors.json')),
    ...parseScheduling(read('SCHEDULING.md')),
  ];

  // ── knowledge ───────────────────────────────────────────────────────────────
  const knowledgeIndex = read(`skills/${slug}-knowledge/SKILL.md`);
  const knowledge: KnowledgeItem[] = [...byPath.keys()]
    .filter((p) => p.startsWith('knowledge/'))
    .sort()
    .map((p, i) => {
      const filename = p.slice('knowledge/'.length);
      const file = byPath.get(p)!;
      return {
        id: `kn_import_${i}`,
        filename,
        mimeType: guessMime(filename),
        sizeBytes: file.sizeBytes ?? byteLength(file.content),
        storageKey: '',
        purpose: knowledgePurpose(knowledgeIndex, filename),
        loadStrategy: knowledgePreloaded(knowledgeIndex, filename)
          ? ('preload-skill' as const)
          : ('reference' as const),
      };
    });

  // ── leftovers ───────────────────────────────────────────────────────────────
  const claimed = new Set<string>([
    '.claude-plugin/plugin.json',
    '.claude-plugin/marketplace.json',
    '.mcp.json',
    '.env.example',
    'README.md',
    'CHANGELOG.md',
    'LICENSE',
    'SCHEDULING.md',
    'settings.json',
    'install.sh',
    'hooks/hooks.json',
    'monitors/monitors.json',
    `agents/${slug}.md`,
    'scripts/run.sh',
  ]);
  for (const path of byPath.keys()) {
    if (claimed.has(path)) continue;
    if (path.startsWith('agents/') || path.startsWith('skills/') || path.startsWith('knowledge/')) continue;
    if (path.startsWith('scripts/') && triggers.some((t) => t.kind === 'conditional' && t.via === 'hook' && `scripts/${t.name}.sh` === path))
      continue;
    unhandled.push({ path, reason: 'No spec field maps to this file; it will not be re-emitted on export.' });
  }

  const spec = agentSpecSchema.parse({
    specVersion: 1,
    meta,
    goal,
    workflows,
    subAgents,
    orchestration,
    skills,
    connectors,
    triggers,
    knowledge,
    packaging: {
      format: 'plugin-zip',
      includeMarketplaceManifest: byPath.has('.claude-plugin/marketplace.json'),
      includeInstallScript: byPath.has('install.sh'),
    },
  });

  return { spec, unhandled };
}

// ── section parsing ───────────────────────────────────────────────────────────

/** Split a generated markdown body on its `#`/`##` headings, preserving order. */
function splitSections(body: string): Record<string, string> {
  const out: Record<string, string> = {};
  let heading = '';
  let buffer: string[] = [];
  const flush = () => {
    if (heading) out[heading] = buffer.join('\n').trim();
    buffer = [];
  };
  for (const line of body.split('\n')) {
    if (/^#{1,2} /.test(line)) {
      flush();
      heading = line.trim();
    } else {
      buffer.push(line);
    }
  }
  flush();
  return out;
}

function bullets(section: string): string[] {
  return section
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l.startsWith('- '))
    .map((l) => l.slice(2).trim());
}

function extractTone(objective: string): string {
  const match = objective.match(/^\*\*Tone:\*\*\s*(.+)$/m);
  return match ? match[1]!.trim() : '';
}

function stripTone(objective: string): string {
  const text = objective
    .split('\n')
    .filter((l) => !l.trim().startsWith('**Tone:**'))
    .join('\n')
    .trim();
  return text === '_No objective set yet._' ? '' : text;
}

const GENERATED_AGENT_HEADINGS = ['# Assigned work', '# What "done" means for the overall goal', '# Reporting'];

function stripGeneratedAgentSections(body: string): string {
  const lines = body.split('\n');
  const cut = lines.findIndex((l) => GENERATED_AGENT_HEADINGS.includes(l.trim()));
  return (cut === -1 ? body : lines.slice(0, cut).join('\n')).trim();
}

/** Reads the `# Assigned work` block a sub-agent file carries back into workflow steps. */
function parseAssignedWork(body: string): Map<string, string[]> {
  const out = new Map<string, string[]>();
  const start = body.indexOf('# Assigned work');
  if (start === -1) return out;
  const end = GENERATED_AGENT_HEADINGS.slice(1)
    .map((h) => body.indexOf(h))
    .filter((i) => i > start)
    .sort((a, b) => a - b)[0];

  const section = body.slice(start, end === undefined ? undefined : end);
  let title = '';
  let steps: string[] = [];
  const flush = () => {
    if (title) out.set(title, steps);
    steps = [];
  };
  for (const line of section.split('\n')) {
    if (line.startsWith('## ')) {
      flush();
      title = line.slice(3).trim();
      continue;
    }
    const step = line.match(/^\d+\. (.+)$/);
    if (step) steps.push(step[1]!.trim());
  }
  flush();
  return out;
}

function stripSupportingSection(body: string): string {
  const idx = body.indexOf('## Supporting files');
  return (idx === -1 ? body : body.slice(0, idx)).trim();
}

function splitTriggerHint(description: string): {
  description: string;
  trigger: SubAgent['trigger']['kind'];
} {
  for (const kind of ['explicit', 'always-background'] as const) {
    const hint = TRIGGER_HINT[kind];
    if (description.endsWith(hint)) {
      return { description: description.slice(0, -hint.length).trim(), trigger: kind };
    }
  }
  return { description: description.trim(), trigger: 'auto' };
}

/** Reads the numbered `# Workflow` list the primary-agent emitter produces. */
function parseWorkflows(section: string, agentIdByName: Map<string, string>): Workflow[] {
  const workflows: Workflow[] = [];
  const lines = section.split('\n');
  let current: Workflow | null = null;

  for (const raw of lines) {
    const header = raw.match(/^(\d+)\. \*\*(.+?)\*\*(?: — (.*))?$/);
    if (header) {
      if (current) workflows.push(current);
      current = {
        id: `wf_import_${header[1]}`,
        title: header[2]!,
        description: header[3] ?? '',
        order: workflows.length,
        steps: [],
        promoteToSkill: false,
        assignedSubAgentIds: [],
      };
      continue;
    }
    if (!current) continue;

    const line = raw.trim();
    const run = line.match(/^Run `\/(.+?)`\.$/);
    if (run) {
      current.promoteToSkill = true;
      current.skillOverrides = { ...current.skillOverrides, name: run[1]! };
      continue;
    }
    const delegate = line.match(/^Delegate to: (.+)$/);
    if (delegate) {
      current.assignedSubAgentIds = [...delegate[1]!.matchAll(/`([^`]+)`/g)]
        .map((m) => agentIdByName.get(m[1]!))
        .filter((id): id is string => Boolean(id));
      continue;
    }
    if (line.startsWith('- ')) current.steps.push(line.slice(2).trim());
  }
  if (current) workflows.push(current);
  return workflows;
}

/** Reads the stage headings the orchestration templates produce. */
function parseDelegation(
  section: string,
  agentIdByName: Map<string, string>,
): AgentSpec['orchestration'] {
  const groups: AgentSpec['orchestration']['groups'] = [];
  const joinLines: string[] = [];

  const blocks = section.split(/\n\n+/);
  for (const block of blocks) {
    const header = block.match(/^\*\*Stage (\d+)\*\* \((concurrent|sequential)\)/);
    if (!header) {
      const trimmed = block.trim();
      if (
        trimmed &&
        !trimmed.startsWith('Only move to the next stage') &&
        !trimmed.startsWith('Use `')
      ) {
        joinLines.push(trimmed);
      }
      continue;
    }
    const ids = [...block.matchAll(/`([a-z0-9-]+)`/g)]
      .map((m) => agentIdByName.get(m[1]!))
      .filter((id): id is string => Boolean(id));
    groups.push({
      id: `og_import_${header[1]}`,
      mode: header[2] === 'concurrent' ? 'parallel' : 'series',
      subAgentIds: [...new Set(ids)],
      order: groups.length,
    });
  }

  return { groups, joinPolicy: joinLines.join('\n\n') };
}

// ── file parsing ──────────────────────────────────────────────────────────────

function parseMcp(
  mcpJson: string | undefined,
  envExample: string | undefined,
  primaryTools: string | undefined,
  readme: string,
): McpServer[] {
  const parsed = readJson(mcpJson);
  if (!parsed) return [];
  const docs = parseEnvDocs(envExample);
  // The per-server tool allowlist only survives in the emitted `mcp__key__tool` patterns.
  const allowlists = new Map<string, string[]>();
  for (const pattern of parseList(primaryTools)) {
    const parts = pattern.split('__');
    if (parts[0] !== 'mcp' || parts.length < 3) continue;
    const key = parts[1]!;
    allowlists.set(key, [...(allowlists.get(key) ?? []), parts.slice(2).join('__')]);
  }
  const prose = parseConnectorProse(readme);

  return Object.entries(obj(parsed.mcpServers)).map(([key, value], i) => {
    const server = obj(value);
    const transport = (str(server.type) || 'stdio') as McpServer['transport'];
    const env: EnvVar[] = Object.entries(obj(server.env)).map(([name, raw]) => {
      const literal = String(raw);
      const placeholder = /^\$\{.+\}$/.test(literal);
      return {
        name,
        required: docs.get(name)?.required ?? true,
        description: docs.get(name)?.description ?? '',
        secret: placeholder,
        defaultValue: placeholder ? '' : literal,
      };
    });

    return {
      id: `mcp_import_${i}`,
      key,
      displayName: prose.get(key)?.displayName ?? '',
      description: prose.get(key)?.description ?? '',
      transport,
      command: str(server.command),
      args: arr(server.args).map(String),
      url: str(server.url),
      env,
      toolAllowlist: allowlists.get(key) ?? [],
      source: 'custom' as const,
      docsUrl: prose.get(key)?.docsUrl ?? '',
    };
  });
}

/** Display name, blurb and docs link only exist in the README's connector section. */
function parseConnectorProse(
  readme: string,
): Map<string, { displayName: string; description: string; docsUrl: string }> {
  const out = new Map<string, { displayName: string; description: string; docsUrl: string }>();
  const blocks = readme.split(/^### /m).slice(1);
  for (const block of blocks) {
    const header = block.match(/^`([a-z0-9_-]+)`(?: — (.+))?/);
    if (!header) continue;
    const lines = block.split('\n').slice(1).map((l) => l.trim());
    const docs = lines.find((l) => l.startsWith('Docs: '))?.slice('Docs: '.length) ?? '';
    const description =
      lines.find(
        (l) =>
          l &&
          !l.startsWith('Docs: ') &&
          !l.startsWith('Transport: ') &&
          !l.startsWith('Environment variables:') &&
          !l.startsWith('- '),
      ) ?? '';
    out.set(header[1]!, { displayName: header[2] ?? '', description, docsUrl: docs });
  }
  return out;
}

/** `.env.example` carries the descriptions and required/optional flags `.mcp.json` cannot. */
function parseEnvDocs(source: string | undefined): Map<string, { description: string; required: boolean }> {
  const out = new Map<string, { description: string; required: boolean }>();
  if (!source) return out;
  let description = '';
  let required = true;
  for (const line of source.split('\n')) {
    const trimmed = line.trim();
    if (trimmed.startsWith('# ── ') || trimmed.startsWith('# docs:')) continue;
    if (/^# (required|optional)/.test(trimmed)) {
      required = trimmed.startsWith('# required');
      continue;
    }
    if (trimmed.startsWith('#')) {
      description = trimmed.slice(1).trim();
      continue;
    }
    const assignment = trimmed.match(/^([A-Z][A-Z0-9_]*)=/);
    if (assignment) {
      out.set(assignment[1]!, { description, required });
      description = '';
      required = true;
    }
  }
  return out;
}

function parsePermissions(readme: string, servers: McpServer[]): AgentSpec['connectors']['permissionsHint'] {
  const match = readme.match(/## Recommended permissions[\s\S]*?```json\n([\s\S]*?)```/);
  if (!match) return { allow: [], deny: [] };
  const parsed = readJson(match[1]);
  const permissions = obj(parsed?.permissions);
  // The compiler folds MCP patterns into `allow`; strip them back out so the next compile
  // does not double-add them.
  const derived = new Set(
    servers.flatMap((s) =>
      s.toolAllowlist.length > 0 ? s.toolAllowlist.map((t) => `mcp__${s.key}__${t}`) : [`mcp__${s.key}`],
    ),
  );
  return {
    allow: arr(permissions.allow).map(String).filter((p) => !derived.has(p)),
    deny: arr(permissions.deny).map(String),
  };
}

function parseHooks(hooksJson: string | undefined, byPath: Map<string, SourceFile>): Trigger[] {
  const parsed = readJson(hooksJson);
  if (!parsed) return [];
  const out: Trigger[] = [];
  let i = 0;

  for (const [event, entries] of Object.entries(obj(parsed.hooks))) {
    for (const entry of arr(entries)) {
      const e = obj(entry);
      for (const hook of arr(e.hooks)) {
        const command = str(obj(hook).command);
        const scriptPath = command.replace('${CLAUDE_PLUGIN_ROOT}/', '');
        const name = scriptPath.replace(/^scripts\//, '').replace(/\.sh$/, '') || 'on-event';
        out.push({
          id: `tr_import_${i++}`,
          kind: 'conditional',
          via: 'hook',
          event: event as never,
          matcher: str(e.matcher),
          name,
          command: extractHookBody(byPath.get(scriptPath)?.content ?? ''),
        });
      }
    }
  }
  return out;
}

/** Recover the user's command from the generated wrapper script. */
function extractHookBody(script: string): string {
  const marker = 'export CLAUDE_HOOK_PAYLOAD="$payload"';
  const idx = script.indexOf(marker);
  if (idx === -1) return script.trim();
  const body = script.slice(idx + marker.length).trim();
  return body === '# TODO: implement this hook.\necho "$payload" >/dev/null' ? '' : body;
}

function parseMonitors(monitorsJson: string | undefined): Trigger[] {
  const parsed = readJson(monitorsJson);
  if (!parsed) return [];
  return arr(parsed.monitors).map((raw, i) => {
    const m = obj(raw);
    return {
      id: `tr_monitor_${i}`,
      kind: 'conditional' as const,
      via: 'monitor' as const,
      config: {
        name: str(m.name),
        check: str(obj(m.check).command),
        intervalSeconds: Number(m.intervalSeconds) || 300,
        prompt: str(m.prompt),
      },
    };
  });
}

/** Reads the schedule table `SCHEDULING.md` renders. */
function parseScheduling(doc: string | undefined): Trigger[] {
  if (!doc) return [];
  const out: Trigger[] = [];
  let i = 0;
  for (const line of doc.split('\n')) {
    const row = line.match(/^\| `(.+?)` \| (.+?) \| .*? \| (.*?) \|$/);
    if (!row) continue;
    const prompt = row[3]!.trim();
    out.push({
      id: `tr_sched_${i++}`,
      kind: 'scheduled',
      cron: row[1]!,
      timezone: row[2]!.trim(),
      prompt: prompt === '_(no prompt)_' ? '' : prompt.replace(/\\\|/g, '|'),
    });
  }
  return out;
}

function parseChangelog(doc: string | undefined): string {
  if (!doc) return '';
  const lines = doc.split('\n');
  const start = lines.findIndex((l) => l.startsWith('## '));
  if (start === -1) return '';
  const rest = lines.slice(start + 1);
  const end = rest.findIndex((l) => l.startsWith('## '));
  const entry = (end === -1 ? rest : rest.slice(0, end)).join('\n').trim();
  return entry === 'Initial release.' ? '' : entry;
}

function knowledgePurpose(index: string | undefined, filename: string): string {
  if (!index) return '';
  const line = index.split('\n').find((l) => l.includes(`knowledge/${filename}\``));
  const match = line?.match(/` — (.+)$/);
  const purpose = match?.[1]?.trim() ?? '';
  return purpose === 'reference material' ? '' : purpose;
}

function knowledgePreloaded(index: string | undefined, filename: string): boolean {
  if (!index) return false;
  const loaded = index.split('## Read on demand')[0] ?? '';
  return loaded.includes(`knowledge/${filename}\``);
}

// ── tiny helpers ──────────────────────────────────────────────────────────────

function normalize(path: string): string {
  return path.replace(/^\.\//, '').replace(/\\/g, '/');
}

function readJson(source: string | undefined): Record<string, unknown> | null {
  if (!source) return null;
  try {
    const parsed = JSON.parse(source);
    return parsed && typeof parsed === 'object' ? (parsed as Record<string, unknown>) : null;
  } catch {
    return null;
  }
}

function obj(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

function arr(value: unknown): unknown[] {
  return Array.isArray(value) ? value : [];
}

function str(value: unknown): string {
  return typeof value === 'string' ? value : '';
}

function byteLength(text: string): number {
  return new TextEncoder().encode(text).length;
}

const MIME: Record<string, string> = {
  md: 'text/markdown',
  txt: 'text/plain',
  json: 'application/json',
  csv: 'text/csv',
  pdf: 'application/pdf',
  yaml: 'application/yaml',
  yml: 'application/yaml',
};

function guessMime(filename: string): string {
  const ext = filename.split('.').pop()?.toLowerCase() ?? '';
  return MIME[ext] ?? 'application/octet-stream';
}

export { parseFrontmatter } from './frontmatter.ts';
