import type { AgentSpec } from '@agent-spawner/spec';
import { describeOrchestration } from '../orchestration.ts';
import { allSkills } from '../promote.ts';
import type { CompiledFile } from '../types.ts';
import { bulletList, json, markdown, oneLine, uniq } from '../util.ts';
import { licenseText } from './licenses.ts';
import { describeCron } from './schedule.ts';
import { mcpPatterns } from './tools.ts';

/** `README.md`, `CHANGELOG.md`, `LICENSE`. */
export function emitDocs(spec: AgentSpec): CompiledFile[] {
  const files: CompiledFile[] = [
    {
      path: 'README.md',
      content:
        spec.meta.readme.mode === 'custom' && spec.meta.readme.body
          ? ensureTrailingNewline(spec.meta.readme.body)
          : generateReadme(spec),
    },
    { path: 'CHANGELOG.md', content: changelog(spec) },
  ];

  const license = licenseText(spec.meta);
  if (license) files.push({ path: 'LICENSE', content: license });

  return files;
}

/** Exported so the Misc tab can seed the custom-README editor with the generated version. */
export function generateReadme(spec: AgentSpec): string {
  const { meta, goal } = spec;
  const repo = repoSlug(spec);
  const skills = allSkills(spec);

  const subAgentTable =
    spec.subAgents.length > 0
      ? [
          '| Agent | When it is used | Model | Runs |',
          '|---|---|---|---|',
          ...spec.subAgents.map(
            (a) =>
              `| \`${a.name}\` | ${escapeCell(a.description) || '—'} | ${a.runtime.model} | ${
                a.runtime.background ? 'background' : 'foreground'
              }${a.runtime.isolation ? ' · own worktree' : ''} |`,
          ),
        ].join('\n')
      : null;

  const skillTable =
    skills.length > 0
      ? [
          '| Skill | Invocation | What it does |',
          '|---|---|---|',
          ...skills.map(
            (s) =>
              `| \`${s.name}\` | ${invocationLabel(s)} | ${escapeCell(oneLine(s.description)) || '—'} |`,
          ),
        ].join('\n')
      : null;

  const connectorBlock =
    spec.connectors.mcpServers.length > 0
      ? spec.connectors.mcpServers
          .map((s) =>
            markdown([
              `### \`${s.key}\`${s.displayName ? ` — ${s.displayName}` : ''}`,
              s.description,
              s.docsUrl ? `Docs: ${s.docsUrl}` : null,
              `Transport: \`${s.transport}\` · Tools: ${mcpPatterns(s).map((p) => `\`${p}\``).join(', ')}`,
              s.env.length > 0
                ? `Environment variables:\n${s.env
                    .map(
                      (v) =>
                        `- \`${v.name}\`${v.required ? '' : ' _(optional)_'} — ${
                          v.description || 'no description'
                        }${v.secret ? ' **· secret, never commit this**' : ''}`,
                    )
                    .join('\n')}`
                : null,
            ]),
          )
          .join('\n')
      : null;

  const permissions = permissionsSnippet(spec);
  const scheduled = spec.triggers.filter((t) => t.kind === 'scheduled');
  const hooks = spec.triggers.filter((t) => t.kind === 'conditional' && t.via === 'hook');
  const monitors = spec.triggers.filter((t) => t.kind === 'conditional' && t.via === 'monitor');

  return markdown([
    `# ${meta.name}`,
    meta.description,
    meta.versionMode === 'pinned'
      ? `\`v${meta.version}\` · generated by [Agent Spawner](https://github.com/) from an \`AgentSpec\`.`
      : 'Tracks every commit — Claude Code resolves the version from the git commit SHA.',

    '## Install',
    '```bash\n' +
      `/plugin marketplace add ${repo}\n` +
      `/plugin install ${meta.slug}@${meta.slug}\n` +
      '```',
    meta.defaultEnabled
      ? null
      : '> This plugin ships with `defaultEnabled: false` because it costs money or reaches external services. Enable it explicitly per project.',

    '## What it does',
    goal.statement || '_No objective recorded._',
    goal.successCriteria.length > 0 ? '### Success criteria' : null,
    goal.successCriteria.length > 0 ? bulletList(goal.successCriteria) : null,
    goal.outOfScope.length > 0 ? '### Out of scope' : null,
    goal.outOfScope.length > 0 ? bulletList(goal.outOfScope) : null,

    spec.workflows.length > 0 ? '## Workflow' : null,
    spec.workflows.length > 0
      ? [...spec.workflows]
          .sort((a, b) => a.order - b.order)
          .map((w, i) => `${i + 1}. **${w.title || 'Untitled'}** — ${w.description || ''}`.trimEnd())
          .join('\n')
      : null,

    subAgentTable ? '## Sub-agents' : null,
    subAgentTable,
    spec.orchestration.groups.length > 0 ? '### Orchestration' : null,
    spec.orchestration.groups.length > 0 ? bulletList(describeOrchestration(spec)) : null,
    spec.orchestration.joinPolicy ? `**Joining results:** ${spec.orchestration.joinPolicy}` : null,

    skillTable ? '## Skills' : null,
    skillTable,

    connectorBlock ? '## Connectors' : null,
    connectorBlock,
    connectorBlock
      ? 'Copy `.env.example` to `.env` and fill in the values. **No credentials are stored in this bundle** — the MCP manifest only contains `${VAR}` placeholders.'
      : null,

    permissions ? '## Recommended permissions' : null,
    permissions
      ? 'A plugin\'s `settings.json` cannot carry permissions. Paste this into the consuming project\'s `.claude/settings.json`:'
      : null,
    permissions ? '```json\n' + permissions + '\n```' : null,

    perAgentWorkaround(spec),

    scheduled.length > 0 ? '## Schedule' : null,
    scheduled.length > 0
      ? `${scheduled
          .map((t) => (t.kind === 'scheduled' ? `- \`${t.cron}\` (${t.timezone}) — ${describeCron(t.cron)}` : ''))
          .join('\n')}\n\nSee [SCHEDULING.md](./SCHEDULING.md) — a plugin cannot schedule itself, so this needs one setup step on your side.`
      : null,

    hooks.length > 0 ? '## Hooks' : null,
    hooks.length > 0
      ? `${hooks
          .map((t) => (t.kind === 'conditional' && t.via === 'hook' ? `- \`${t.event}\`${t.matcher ? ` matching \`${t.matcher}\`` : ''} → \`scripts/${t.name}.sh\`` : ''))
          .join('\n')}\n\n> These scripts run on your machine with your permissions whenever the event fires. Read them before enabling the plugin.`
      : null,

    monitors.length > 0 ? '## Monitors (experimental)' : null,
    monitors.length > 0
      ? 'Monitors are an experimental Claude Code component and the format may change. See `monitors/monitors.json`.'
      : null,

    spec.knowledge.length > 0 ? '## Bundled knowledge' : null,
    spec.knowledge.length > 0
      ? spec.knowledge
          .map(
            (k) =>
              `- \`knowledge/${k.filename}\` (${formatBytes(k.sizeBytes)}) — ${k.purpose || 'reference material'}${
                k.loadStrategy === 'preload-skill' ? ' _(preloaded via the generated index skill)_' : ''
              }`,
          )
          .join('\n')
      : null,

    meta.dependencies.length > 0 ? '## Requires' : null,
    meta.dependencies.length > 0
      ? meta.dependencies.map((d) => `- \`${d.name}\`${d.constraint ? ` \`${d.constraint}\`` : ''}`).join('\n')
      : null,

    '## Updating',
    meta.versionMode === 'pinned'
      ? 'Bump `version` in `.claude-plugin/plugin.json` and push. Claude Code will not offer an update until the version changes.'
      : 'Push to the tracked branch; Claude Code resolves the version from the commit SHA, so every commit is an update.',

    meta.license === 'UNLICENSED' ? null : `## License\n\n${meta.license}`,
  ]);
}

function perAgentWorkaround(spec: AgentSpec): string | null {
  // Plugin agents cannot carry per-agent MCP servers or permission modes. If the spec implies
  // either, tell the user what to put in their own settings instead of silently dropping it.
  const needsPerAgentMcp = spec.subAgents.some((a) =>
    a.tools.allow.some((t) => t.startsWith('mcp__')),
  );
  if (!needsPerAgentMcp) return null;

  return markdown([
    '## Per-agent MCP access',
    'Plugin-packaged agents may not declare their own `mcpServers` or `permissionMode` — Claude Code rejects those keys for security reasons. The connectors in `.mcp.json` are available to the whole project, and each agent narrows them through its `tools` allowlist.',
    'If you need a connector scoped to one agent only, define that agent locally in `.claude/agents/` in your project rather than through this plugin.',
  ]);
}

/** The `permissions.allow` / `permissions.deny` block, also previewed live in the Connectors tab. */
export function permissionsSnippet(spec: AgentSpec): string | null {
  const allow = uniq([
    ...spec.connectors.permissionsHint.allow,
    ...spec.connectors.mcpServers.flatMap(mcpPatterns),
  ]);
  const deny = uniq(spec.connectors.permissionsHint.deny);
  if (allow.length === 0 && deny.length === 0) return null;
  return json({ permissions: { allow, deny } }).trimEnd();
}

function changelog(spec: AgentSpec): string {
  const entry = spec.meta.changelogEntry.trim() || 'Initial release.';
  const heading =
    spec.meta.versionMode === 'pinned' ? `## ${spec.meta.version}` : '## Unreleased';
  return markdown(['# Changelog', heading, entry]);
}

function repoSlug(spec: AgentSpec): string {
  if (spec.deployment?.repo.owner && spec.deployment.repo.name) {
    return `${spec.deployment.repo.owner}/${spec.deployment.repo.name}`;
  }
  const match = spec.meta.repository.match(/github\.com[/:]([^/]+)\/([^/.]+)/);
  if (match) return `${match[1]}/${match[2]}`;
  return '<owner>/<repo>';
}

function invocationLabel(skill: { disableModelInvocation: boolean; userInvocable: boolean; name: string }): string {
  if (skill.disableModelInvocation) return `manual only (\`/${skill.name}\`)`;
  if (!skill.userInvocable) return 'background knowledge';
  return `automatic or \`/${skill.name}\``;
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}

function ensureTrailingNewline(text: string): string {
  return text.endsWith('\n') ? text : `${text}\n`;
}
